### ISSUE TITLE
Confusions about data in the main.lua

### ISSUE THREAD

**Issue by SJTUsuperxu** [viorik/ConvLSTM#19]
Hello  viorik @viorik 
     Recently I have been trying to implement conv-lstm for my video processing task. I have read your "spatio-temporal video autoencoder" paper and It is really a good one. After reading your source code, I  had several problems about the data in main.lua.
    The program "getdataSeq_mnist.lua" is mainly for generation of samples, right? But I'm not certain about the data format: here 'data' is a 5-D dim? 1 for samples, and 2 for sequence length? 3 for channels? 4/5 for width/height.  If so, I cannot understand the meanings of 
`       sample = dataset[t]
        data = sample[1]
        for i = 1,data:size(1)-1 do
          table.insert(inputTable, data[i]:cuda())
        end
`  
Here sample should be a sample, and data should be a sequence?? right? If so, data:size(1) should  equal to 1 ?  I'm sorry but I'm confused about the data format here. 
        Could you please explain it a little? Thanks.

**Comment by viorik** [comment]
Hi @SJTUsuperxu,
If you look in `data_mnist.lua`, line 29, the sample size is `(nseq,1,nrows,ncols)`, so the first dimension equalling to 1 disappears when copying the sample in `data_mnist.lua`, line 33. So data:size(1) in main is the length of the sequence.

**Comment by SJTUsuperxu** [comment]
Wow, that's clear! Thank you very much @viorik

**Comment by SJTUsuperxu** [comment]
Hi @viorik 
I'm sorry but I still have a question about how you create this dataset. The parameter nseq is the number of time-steps?  If so, you create the dataset by iterating the images in a segment? I mean, for example, there are 10 images in original video which we want to process. And imagine the number of time-steps is 3. we create the dataset like this: {{img_1, img_2, img3}, {img_2, img_3, img_4}, ... {img_8, img_9, img_10}} And there are total 8 samples. The dataset is created in this way or in some other way?? Thanks~

**Comment by viorik** [comment]
Hi @SJTUsuperxu 
You have two options. Assuming you have sequences of length N, you can use a model with N time steps, and call `forget()` after each training iteration (forward-backward-update) to erase the memory, OR use shorter consecutive subsequences like you said, but in that case you call `forget()` only after you've run training iterations with all the consecutive subsequences of a sequence. In my example, I used the first option, which I observed gives a more stable training because in the second option, you keep the memory between consecutive subsequences, but in each iteration the memory was computed with the weights from the previous iteration. So the first option is preferable if you have enough gpu memory, otherwise use the second option.

**Comment by SJTUsuperxu** [comment]
Thank you @viorik 
I think I got it. (I'm sorry to interrupt you because I am new in lstm).Each sample in your "mnist-fly" dataset represents a video,  and nseq = N(the number of frames in the video). Then, model can be used by N time steps. 
Thank you very much. That's very nice of you.
