### ISSUE TITLE
Compatibility with nn.BiSequencer()

### ISSUE THREAD

**Issue by jxchen01** [viorik/ConvLSTM#7]
Is the convLSTM block compatible with BiSequencer of the rnn package? To my understanding, there seems to be no problem. But, my test encountered the following error: 

all/share/lua/5.1/extracunn/SpatialConvolutionNoBias.lua:94: attempt to call field 'SpatialConvolutionMMNoBias_updateOutput' (a nil value)

(extracunn has been installed.)

Thanks!

**Comment by viorik** [comment]
Hi @jxchen01 , I haven't tested it with the BiSequencer, but as you say, I don't see why this wouldn't work. Could you please put here a simple model and I'll have a look?
By the way, make sure your model and tensors are both on cuda, since SpatialConvolutionNoBias is implemented only for cuda tensors.

**Comment by jxchen01** [comment]
@viorik , Thanks a lot for your reminder. I was not aware of that SpatialConvolutionNoBias cannot work with CPU. After shipping everything to GPU, there is no issue any longer. That is, the convLSTM block is totally compatible with BiSequencer(). 

Huray!
